#!/usr/bin/env bash
#
# model-bridge one-click install. Generates secrets, builds the
# Docker image, and brings the stack (PostgreSQL + backend) up.
#
set -euo pipefail

cd "$(dirname "$0")"

# ── 0. Sanity ────────────────────────────────────────────────────
if ! command -v docker >/dev/null 2>&1; then
  echo "✗ docker not found. Install Docker Desktop or Docker Engine first." >&2
  exit 1
fi

if docker compose version >/dev/null 2>&1; then
  DC=(docker compose)
elif command -v docker-compose >/dev/null 2>&1; then
  DC=(docker-compose)
else
  echo "✗ Docker Compose not found (looked for 'docker compose' and 'docker-compose')." >&2
  exit 1
fi

if ! command -v openssl >/dev/null 2>&1; then
  echo "✗ openssl not found — required to generate secrets." >&2
  exit 1
fi

# ── 1. Generate .env on first run ────────────────────────────────
if [ ! -f .env ]; then
  echo "→ generating .env with random secrets"
  PG_PASSWORD=$(openssl rand -hex 16)
  cat > .env <<EOF
# model-bridge — generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
PORT=3000
HOST=0.0.0.0

# PostgreSQL credentials (the bundled postgres container reads these)
PG_USER=model_bridge
PG_PASSWORD=${PG_PASSWORD}
PG_DATABASE=model_bridge
DATABASE_URL=postgres://model_bridge:${PG_PASSWORD}@postgres:5432/model_bridge

ENCRYPTION_KEY=$(openssl rand -hex 32)
JWT_SECRET=$(openssl rand -hex 32)
ADMIN_USERNAME=admin
ADMIN_PASSWORD=admin
EOF
  chmod 600 .env
  echo "  → edit ADMIN_PASSWORD in .env before exposing the dashboard"
else
  echo "→ reusing existing .env"
  # If .env exists but lacks PG settings (upgrade from old SQLite version), top it up.
  if ! grep -q '^PG_PASSWORD=' .env; then
    echo "  → .env is missing PostgreSQL settings, appending them now"
    PG_PASSWORD=$(openssl rand -hex 16)
    cat >> .env <<EOF

# PostgreSQL credentials (added on $(date -u +%Y-%m-%dT%H:%M:%SZ))
PG_USER=model_bridge
PG_PASSWORD=${PG_PASSWORD}
PG_DATABASE=model_bridge
DATABASE_URL=postgres://model_bridge:${PG_PASSWORD}@postgres:5432/model_bridge
EOF
    echo "  → if you had a SQLite database under ./data/, run ./migrate-to-pg.sh to import it"
  fi
fi

# ── 2. Build and start ────────────────────────────────────────────
echo "→ building and starting the stack"
"${DC[@]}" up -d --build

echo
echo "✔ model-bridge is up"
echo "  dashboard:  http://localhost:3001"
echo "  default:    admin / admin   ← change this under Settings now"
echo "  oauth port: 1455 (browser callback for OpenAI / Google)"
echo
echo "Stop:   ${DC[*]} down"
echo "Logs:   ${DC[*]} logs -f"
